language: node_js
services:
  - mongodb
node_js:
  - v8
script:
  - npm run lint && npm test
  - npm run build
  - npm run report-coverage
cache:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
